### ISSUE TITLE
Extracting tables using run-web-app

### ISSUE THREAD

**Issue by igormis** [Unstructured-IO/pipeline-sec-filings#162]
Is there positibility to extract also the tables not just the NarrativeText from the xbrl file using some parameter to the app?

**Comment by cragwolfe** [comment]
@igormis , this repo is no longer under active development. Table extraction from xml, html or PDF doc types (and others) continues to improve in the https://github.com/Unstructured-IO/unstructured library, so i suggest trying that out. In particular, html docs do pretty well right now, so html versions SEC filings may get you what you need.
