### ISSUE TITLE
Rename the sample-sec-docs/ folder

### ISSUE THREAD

**Issue by cragwolfe** [Unstructured-IO/pipeline-sec-filings#68]
The convention for preprocessing pipeline repos is to place sample documents in the `sample-docs/` folder.

Pipeline-sec-filings should follow this convention, i.e. [sample-sec-docs/](https://github.com/Unstructured-IO/pipeline-sec-filings/tree/542169e/sample-sec-docs) should be moved do `sample-docs/`.

**Definition of Done**

* The directory is moved, and the Makefile and tests are updated, e.g. starting with [make dl-test-artifacts](https://github.com/Unstructured-IO/pipeline-sec-filings/blob/083b56f/Makefile#L136).
* Grep'ing through the repo shows no references to `sample-sec-docs`

**Comment by Rishav1707** [comment]
Do we have to rename the `sample-sec-docs/` folder to `sample-docs/` folder only?

**Comment by cragwolfe** [comment]
@Rishav1707 , that is correct.
